{{- $namespace := .Release.Namespace -}}

{{- $vaultName := .Values.app.akvName -}}

{{- if .Values.app.appDynamics.enable }}

apiVersion: spv.no/v1alpha1

kind: AzureKeyVaultSecret

metadata:

  name: {{ .Values.app.appDynamics.akvSecretName }}

  namespace: {{ .Release.Namespace }}

spec:

  vault:

    name: {{ .Values.app.akvName }}

    object:

      name: {{ .Values.app.appDynamics.akvSecretName }}

      type: secret

  output:

    secret:

      name: {{ .Values.app.appDynamics.akvSecretName }}

      dataKey: appd-key

{{- end }}

---

apiVersion: spv.no/v1alpha1

kind: AzureKeyVaultSecret

metadata:

  name: rxwa-ingress-certs-{{ .Values.app.containers.envCode }}

  namespace: istio-system

spec:

  vault:

    name: {{ $vaultName }}

    object:

      name: {{ .Values.app.akvCerts }}

      type: certificate

  output:

    secret:

      name: rxwa-ingress-certs-{{ .Values.app.containers.envCode }}  # kubernetes secret name

      type: kubernetes.io/tls # kubernetes secret type

      chainOrder: ensureserverfirst

---

{{- range $key, $val := .Values.app.akvSecrets }}

apiVersion: spv.no/v1alpha1

kind: AzureKeyVaultSecret

metadata:

  name: {{ $val }}

  namespace: {{ $namespace }}

spec:

  vault:

    name: {{ $vaultName }} # name of key vault

    object:

      name: {{ $val }} # name of the akv object

      type: secret # akv object type

---

{{- end }}
